---
title: "Demographics_Only"
author: "Bengusu Ozcan"
date: "12/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Based on latest_all

```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(wesanderson)
library(doBy)
library(gt)
#install.packages("kableExtra")
library(kableExtra)
```

```{r}
recoded <- read.csv(file.choose())
```


```{r}
recoded %>% group_by(group) %>% summarise(max=max(age),min=min(age),avg=mean(age),med=median(age))
recoded %>% summarise(max=max(age),min=min(age),avg=mean(age),med=median(age))
```

```{r}
table(recoded$X2_Gender)
```
```{r}
table(recoded$X2_Gender,recoded$group)
```


```{r}
tab1 <- (table(recoded$X3_Education,recoded$group)) 
tab1
``` 
```{r}
table(recoded$X3_Education)
```


```{r}
#tried latex but not using for now
tab1 %>%
  kbl(caption="Table1: Education by Group",
       format= "html",
   col.names = c("Control","Treatment"),
                  align="r") %>%
   kable_classic(full_width = F, html_font = "Source Sans Pro")
```



```{r}
#tried latex didn't work
#\chapter{Creating a table}
#\begin{verbatim}
table_latex <- tab1
print(table_latex,
      latex.environments =  c("scriptsize", "center", "widestuff"),
      tabular.environment = "longtable",
      floating = FALSE
)
#\end{verbatim}

<<CreateTable,  echo=TRUE, results = 'asis'>>=
library("xtable")
table_latex <- tab1
print(table_latex,
      latex.environments =  c("scriptsize", "center", "widestuff"),
      tabular.environment = "longtable",
      floating = FALSE
)
@
```



```{r}
#tried latex but gave error on overleaf
xtable(tab1, type = "latex", file = "tab1.tex")
```


```{r}
#tried latex but didn't work
formattable(tab_educ,
            list(`Indicator Name` = formatter(
              "span", style = ~ style(color = "grey",font.weight = "bold")) 
))
```


```{r}
tab<-recoded%>% group_by(X3_Education,group) %>% summarize(count=n()) %>%  gt(rowname_col="Education Level")
```

```{r}
rec<-recoded %>% 
  group_by(X3_Education,group) %>% summarize(count=n()) %>%   mutate(sumnumeric = sum(c_across(where(is.numeric)), na.rm = T))
```

```{r}
data_wide <- spread(rec, X3_Education, count) %>% gt(rowname_col = "group")
data_wide
```


```{r}
(table(recoded$X4_Income,recoded$group))
```

```{r}
table(recoded$X4_Income)
```


```{r}
(table(recoded$X5_Political,recoded$group))
```
```{r}
table(recoded$X5_Political)
```




***Personalization Demographics***

```{r}
platforms=read.csv(file.choose())
```

```{r}
platforms %>% group_by(X6_Platforms) %>% summarize(count=n()) %>% 
ggplot(aes(x=reorder(X6_Platforms,count),y=count))+geom_bar(stat='identity',position='dodge')+labs(y = "Number of people",
       title = "Whic PSPs Do the Participants Use in Real Life?")+
  theme_minimal()+
    geom_text( aes(label = count),colour = "black", size = 3, vjust = 0.3, hjust=-0.2, position = position_dodge(.8))+theme(axis.title.y=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank())+coord_flip()
```

```{r}
table(recoded$platforms_used,useNA="always")
```


```{r}
platforms %>% filter(platforms_used==1) %>% group_by(X6_Platforms) %>% summarize(count=n()) %>% 
ggplot(aes(x=reorder(X6_Platforms,count),y=count))+geom_bar(stat='identity',position='dodge')+labs(y = "Number of people",
       title = "Participants Using only One PSP")+
  theme_minimal()+
    geom_text(
    aes(label = count),
    colour = "black", size = 3,
    vjust = 0.3, hjust=-0.2, position = position_dodge(.8)) + theme(axis.title.y=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank())+coord_flip()
```


```{r}
(table(recoded$X7_Personalization,recoded$group))
```

```{r}
(table(recoded$X8_Satisfaction,recoded$group))
```



```{r}
(table(recoded$equal_fee,recoded$group))
```


```{r}
recoded %>% group_by(X3_Education) %>% summarise(count=n()) %>% ggplot(aes(x = X3_Education, y=count))+
  geom_bar(stat='identity', position="dodge") +
  labs(x = "Education Level", y = "Number of people",
       title = "Number of People by Education")+
  theme_minimal()+
    geom_text(
    aes(label = count),
    colour = "black", size = 3,
    vjust = 0.1, position = position_dodge(.9)) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```
```{r}
latest_all %>% group_by(X4_Income) %>% summarise(count=n()) %>% ggplot(aes(x = X4_Income, y=count))+
  geom_bar(stat='identity', position="dodge") +
  labs(x = "Income Level", y = "Number of people",
       title = "Table2")+
  theme_minimal()+
    geom_text(
    aes(label = count),
    colour = "black", size = 3,
    vjust = 0.1, position = position_dodge(.9)) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```
```{r}
latest_all %>% group_by(X5_Political) %>% summarise(count=n()) %>% ggplot(aes(x = X5_Political, y=count))+
  geom_bar(stat='identity', position="dodge") +
  labs(x = "Political View", y = "Number of people",
       title = "Table3")+
  theme_minimal()+
    geom_text(
    aes(label = count),
    colour = "black", size = 3,
    vjust = 0.1, position = position_dodge(.9)) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```
```{r}
latest_all %>% group_by(X3_Education, group) %>% summarise(count=n()) %>% ggplot(aes(x = X3_Education, y=count, fill=group))+
  geom_bar(stat='identity', position="dodge") +
  labs(x = "Education Level", y = "Number of people",
       title = "Table4")+
  theme_minimal()+
    geom_text(
    aes(label = count),
    colour = "black", size = 3,
    vjust = 0.1, position = position_dodge(.9)) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```
```{r}
latest_all %>% group_by(X5_Political, group) %>% summarise(count=n()) %>% ggplot(aes(x = X5_Political, y=count, fill=group))+
  geom_bar(stat='identity', position="dodge") +
  labs(x = "Political View", y = "Number of people",
       title = "Table6")+
  theme_minimal()+
    geom_text(
    aes(label = count),
    colour = "black", size = 3,
    vjust = 0.1, position = position_dodge(.9)) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```
```{r}
latest_all %>% group_by(X4_Income,group) %>% summarise(count=n()) %>% ggplot(aes(x = X4_Income, y=count,fill=group))+
  geom_bar(stat='identity', position="dodge") +
  labs(x = "Income Level", y = "Number of people",
       title = "Table7")+
  theme_minimal()+
    geom_text(
    aes(label = count),
    colour = "black", size = 3,
    vjust = 0.1, position = position_dodge(.9)) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```

```{r}
latest_all %>% group_by(equal_fee,X5_Political) %>% summarise(count=n()) %>% ggplot(aes(x = equal_fee, y=count,fill=X5_Political))+
  geom_bar(stat='identity', position="dodge") +
  labs(x = "Equal fee answer", y = "Number of people",
       title = "Equal fee by political view")+
  theme_minimal()+
    geom_text(
    aes(label = count),
    colour = "black", size = 3,
    vjust = 0.1, position = position_dodge(.9)) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```

